#!/bin/bash

echo "🔍 서버 로그 확인을 위한 명령어..."
echo ""
echo "VM에 접속하세요:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "gcloud compute ssh instance-20251204 --zone=asia-northeast3-a"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "VM 접속 후 다음 명령어를 실행하세요:"
echo ""
echo "1️⃣ PM2로 실행 중인 경우:"
echo "   pm2 logs rag-chat --lines 100"
echo ""
echo "2️⃣ systemd로 실행 중인 경우:"
echo "   sudo journalctl -u rag-chat -n 100 --no-pager"
echo ""
echo "3️⃣ Docker로 실행 중인 경우:"
echo "   docker logs pr-webhook-app --tail 100"
echo ""
echo "4️⃣ 실시간 로그 보기:"
echo "   pm2 logs rag-chat --lines 0"
echo ""
echo "5️⃣ 프로세스 상태 확인:"
echo "   pm2 status"
echo "   # 또는"
echo "   ps aux | grep node"
echo ""

